=== grozail/uni-labs-2016/src/grozail/lab12/source/medicine.dtd
<!ELEMENT medicine_list (medicine*)>
<!ELEMENT medicine (name,price,dosage,visual)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT dosage (#PCDATA)>
<!ELEMENT visual (color,body,indications)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT body (#PCDATA)>
<!ELEMENT indications (#PCDATA)>

=== grozail/uni-labs-2016/src/grozail/lab12/source/medicine_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE medicine_list SYSTEM "medicine.dtd">
<medicine_list>
    <medicine>
        <name>Dgsai</name>
        <price>2.04</price>
        <dosage>0.12</dosage>
        <visual>
            <color>красный</color>
            <body>порошкообразный</body>
            <indications>психические заболевания</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Gohjv</name>
        <price>2.35</price>
        <dosage>0.69</dosage>
        <visual>
            <color>белый</color>
            <body>порошкообразный</body>
            <indications>расстройства организма</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Kpefaax</name>
        <price>4.76</price>
        <dosage>0.26</dosage>
        <visual>
            <color>синий</color>
            <body>жидкий</body>
            <indications>респираторные заболевания</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Vufnu</name>
        <price>6.18</price>
        <dosage>0.62</dosage>
        <visual>
            <color>красный</color>
            <body>порошкообразный</body>
            <indications>психические заболевания</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Ibds</name>
        <price>7.5</price>
        <dosage>0.94</dosage>
        <visual>
            <color>красный</color>
            <body>порошкообразный</body>
            <indications>общеукрепляющее</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Tfmvyvu</name>
        <price>7.66</price>
        <dosage>0.28</dosage>
        <visual>
            <color>красный</color>
            <body>жидкий</body>
            <indications>общеукрепляющее</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Ptvgc</name>
        <price>7.97</price>
        <dosage>0.81</dosage>
        <visual>
            <color>черный</color>
            <body>порошкообразный</body>
            <indications>расстройства организма</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Gvttxea</name>
        <price>9.57</price>
        <dosage>0.54</dosage>
        <visual>
            <color>черный</color>
            <body>порошкообразный</body>
            <indications>психические заболевания</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Jsnmjvaypt</name>
        <price>10.36</price>
        <dosage>0.12</dosage>
        <visual>
            <color>синий</color>
            <body>жидкий</body>
            <indications>психические заболевания</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Pecgeaqgak</name>
        <price>10.62</price>
        <dosage>0.53</dosage>
        <visual>
            <color>зеленый</color>
            <body>порошкообразный</body>
            <indications>психические заболевания</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Tncyshyyv</name>
        <price>14.24</price>
        <dosage>0.75</dosage>
        <visual>
            <color>черный</color>
            <body>порошкообразный</body>
            <indications>расстройства организма</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Fcq</name>
        <price>16.24</price>
        <dosage>0.86</dosage>
        <visual>
            <color>черный</color>
            <body>твердый</body>
            <indications>общеукрепляющее</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Bquu</name>
        <price>17.51</price>
        <dosage>0.53</dosage>
        <visual>
            <color>зеленый</color>
            <body>порошкообразный</body>
            <indications>психические заболевания</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Swuxb</name>
        <price>18.71</price>
        <dosage>0.36</dosage>
        <visual>
            <color>белый</color>
            <body>твердый</body>
            <indications>общеукрепляющее</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Bvojwql</name>
        <price>22.86</price>
        <dosage>0.72</dosage>
        <visual>
            <color>синий</color>
            <body>твердый</body>
            <indications>психические заболевания</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Pc</name>
        <price>24.54</price>
        <dosage>0.33</dosage>
        <visual>
            <color>белый</color>
            <body>твердый</body>
            <indications>психические заболевания</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Mti</name>
        <price>27.97</price>
        <dosage>0.53</dosage>
        <visual>
            <color>черный</color>
            <body>твердый</body>
            <indications>психические заболевания</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Cktqrpcxmqchqf</name>
        <price>30.74</price>
        <dosage>0.05</dosage>
        <visual>
            <color>белый</color>
            <body>жидкий</body>
            <indications>расстройства организма</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Klqao</name>
        <price>31.58</price>
        <dosage>0.95</dosage>
        <visual>
            <color>белый</color>
            <body>твердый</body>
            <indications>психические заболевания</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Mohbs</name>
        <price>31.91</price>
        <dosage>0.27</dosage>
        <visual>
            <color>синий</color>
            <body>порошкообразный</body>
            <indications>расстройства организма</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Vluugah</name>
        <price>33.34</price>
        <dosage>0.43</dosage>
        <visual>
            <color>синий</color>
            <body>порошкообразный</body>
            <indications>общеукрепляющее</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Sfnb</name>
        <price>33.87</price>
        <dosage>0.27</dosage>
        <visual>
            <color>синий</color>
            <body>порошкообразный</body>
            <indications>общеукрепляющее</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Qlsap</name>
        <price>36.47</price>
        <dosage>0.9</dosage>
        <visual>
            <color>синий</color>
            <body>твердый</body>
            <indications>расстройства организма</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Vsyyoq</name>
        <price>39.14</price>
        <dosage>0.51</dosage>
        <visual>
            <color>зеленый</color>
            <body>порошкообразный</body>
            <indications>расстройства организма</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Eyvs</name>
        <price>40.17</price>
        <dosage>0.46</dosage>
        <visual>
            <color>красный</color>
            <body>твердый</body>
            <indications>общеукрепляющее</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Rdbjadxq</name>
        <price>51.43</price>
        <dosage>0.51</dosage>
        <visual>
            <color>черный</color>
            <body>порошкообразный</body>
            <indications>расстройства организма</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Fobwasm</name>
        <price>52.14</price>
        <dosage>0.07</dosage>
        <visual>
            <color>белый</color>
            <body>жидкий</body>
            <indications>респираторные заболевания</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Oxlbchoo</name>
        <price>56.41</price>
        <dosage>0.47</dosage>
        <visual>
            <color>зеленый</color>
            <body>порошкообразный</body>
            <indications>респираторные заболевания</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Lbdxfn</name>
        <price>58.55</price>
        <dosage>0.25</dosage>
        <visual>
            <color>белый</color>
            <body>порошкообразный</body>
            <indications>расстройства организма</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Kxkm</name>
        <price>62.45</price>
        <dosage>0.52</dosage>
        <visual>
            <color>красный</color>
            <body>жидкий</body>
            <indications>общеукрепляющее</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Yegwjb</name>
        <price>66.37</price>
        <dosage>0.86</dosage>
        <visual>
            <color>белый</color>
            <body>твердый</body>
            <indications>психические заболевания</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Qbsa</name>
        <price>70.24</price>
        <dosage>0.2</dosage>
        <visual>
            <color>белый</color>
            <body>твердый</body>
            <indications>общеукрепляющее</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Qgtiyly</name>
        <price>80.45</price>
        <dosage>0.0</dosage>
        <visual>
            <color>черный</color>
            <body>порошкообразный</body>
            <indications>расстройства организма</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Nfi</name>
        <price>85.63</price>
        <dosage>0.79</dosage>
        <visual>
            <color>синий</color>
            <body>порошкообразный</body>
            <indications>расстройства организма</indications>
        </visual>
    </medicine>
    <medicine>
        <name>Hytcbwa</name>
        <price>86.25</price>
        <dosage>0.91</dosage>
        <visual>
            <color>зеленый</color>
            <body>жидкий</body>
